version: '3'
services:
  backend:
    build: .
    ports:
      - '8888:8888'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database
  database:
    image: mysql:8.0
    command: --wait_timeout=60 --interactive_timeout=60
    environment:
      MYSQL_ROOT_PASSWORD: rootjin123
      MYSQL_DATABASE: blog
      MYSQL_USER: jin
      MYSQL_PASSWORD: userjin123
    ports:
      - '3304:3306'
    volumes:
      - ./docker-config/database/mysql:/var/lib/mysql
      - ./docker-config/database/my.cnf:/etc/mysql/conf.d/my.cnf
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./docker-config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
